name: .NET

on:
  pull_request:
    types: [ opened ]
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore .7SamuraiAPp.sln
    - name: Build
      run: dotnet build --no-restore .7SamuraiAPp.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal .7SamuraiAPp.sln
